# Generated by Django 5.2.5 on 2025-08-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decryptor', '0002_alter_paymentproof_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='media_url',
            field=models.URLField(max_length=400),
        ),
    ]
